config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
     collection do
      get 'detail'
    end
  resources :reviews, only: [:new, :create, :update]
  resources :users, only: :show
end
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  belongs_to :user
  
  has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image
  has_many :reviews
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image])
  end
  
  def after_sign_out_path_for(resource)
   '/users/sign_in'
  end
  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: :new
  
  def index
    @products = Product.order('created_at DESC').limit(8)
    product_ids = Review.group(:product_id).order('count_product_id DESC').limit(3).count(:product_id).keys
    @ranking = product_ids.map { |id| Product.find(id) }
    @reviews = Review.order(created_at: :DESC).limit(3)
  end
  def detail
    @products = Product.order('created_at DESC').page(params[:page]).per(9)
  end
  
  def new
    @product = Product.new
  end
  
  def create
    Product.create(product_create_params)
    redirect_to controller: :products, action: :index
  end
  
  def show
    @product = Product.find(params[:id])
  end 
  
  private
  def product_create_params
    params.require(:product).permit(:title, :image_url, :explain, :access).merge(user_id: current_user.id)
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  products 'index'
   before_action :ranking
  def ranking
    @ranking = Product.limit(5)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: :index
  
  def new
    @review = Review.new
    @product = Product.find(params[:product_id])
  end
  
  def create
    Review.create(create_params)
    redirect_to controller: :products, action: :index
  end
  
  private
  def create_params
    params.require(:review).permit(:rate, :title, :review).merge(product_id: params[:product_id], user_id: current_user.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @count_reviews = user.reviews
    @reviews = user.reviews.order("created_at DESC").page(params[:page]).per(5)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
    <div class="header">
        <div class="user__info">
          <ul>
            <li class="logo" style="float :left">
              <%= link_to "~温泉物語~", root_path, class:'post' %></li>
            <% if user_signed_in? %>
            <li class="logout" style="float :right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <li class="mypage" style="float: right">
                <a href="/products/:product_id/users/<%= current_user.id %>">マイページ</a>
              </li>

            <li class="new" style="float :right">
              <%= link_to "投稿", new_product_path, class:'post' %></li>
              <%else%>
            <li class="signin" style="float :right", >
              <%= link_to "サインイン", user_session_path, class:'post' %></li>
              <% end %>
              
          </ul>
          <p><i>心地よい温もりをあなたに</i></p>
        </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/products/detail.html.erb
<div class="contents row">
  <div class="post-flame">
    <div class="post-name" style="padding:10px">
      <p>温泉一覧</p>
      <% @products.each do |product|%>
        <div class="post-itiran">
          <a href="/products/<%= product.id %>">
         <div class="title_">
           <%= product.title %>
         </div>
          <div class="image_">
           <img src="<%= product.image_url %>" width="300" height="150"></img>
          </div>
           <div class="text-xsmall">
             <p>
             <%= product.explain.truncate(25) %>
           </p>
           </div>
           </a>
        </div>
       
      
      <% end %>
      <%= paginate(@products)%>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="main-contents">
    <div class="contents">
        <div class="top-image">
            <img src="https://t4.ftcdn.net/jpg/01/97/82/47/240_F_197824759_KUrBatUtl1mKD3lnMbl0rYC8L0gPCpHN.jpg" alt="温泉イメージ" width="1000" height="500"></img>
        </div>
        <div class="portion" style="float:left">
          <p>一覧</p>
              <% @products.each do |product| %>
              <a href="/products/<%= product.id %>">
          <div class="article">
            <div class="article-image">
              <div class="image">
                <img src="<%= product.image_url %>" width="150" height="150">
              </div>
             </div>
              <div class="article-text">
                        <div class="detail-name"><%= product.title %></div>
                        <div class="explain"><%= product.explain.truncate(41) %></div>
                        <div class="access">
                            <%= product.access %></div>
                        <div class="evaluation">
                          <span class="rating-star">
                            <i class="star-actived rate-[ここに評価を表示]0"></i>
                          </span>
                        </div>
              </div>
           </div>
              </a>
              <% end %>
              <h5 style="float:right;padding:10px"><%= link_to 'もっと詳しく一覧表示する','/products/detail'%></h5>
          </div>
         <div class="ranking" style="float:right">
            <p>ランキング</p>
            <% @ranking.each.with_index(1) do |product, i| %>
             <div class="ranking-detail">
                 <a href="/products/<%= product.id %>">
                 <div class="ranking_number"><%= i %></div>
                 <div class="ranking_image" style="text-align:center">
                <img src="<%= product.image_url %>" alt=""width="300" height="200" >
                </div>
                  <p>
                    <%= product.title %>
                  </p>
                </a>
             </div>
            <%end%>
        </div>
    </div>
    <div class="recently" style="float:right">
        <p>最近の口コミ</p>
      <% @reviews.each do |review| %>
       <div class="comment-review">
         <div classs="comment-user">
          <div class="comment-image">
            <img src="<%= review.product.image_url %>" width="100" height="100"></img>
             <div class="comment-image-title"><%= review.product.title %></div>
             <p class="text-small">
             <span class="rating-star"><i class="star-actived rate-<%= review.rate %>0"></i></span>
             </p>
          </div>
         </div>
          
          <div class="comment-info">
            <div class="comment-username"><span><<%= review.user.nickname %>さん></span></%></div>
            <div class="comment-title">
              <%= review.title %></div>
            <div class="comment-comment"><%= review.review%></div>
          </div>
        </div>
         <% end %>
    </div>
</div>
    

app/views/products/new.html.erb
<div style="padding:15px">
<div class="contents row">
    <h3><新規投稿ページ></h3>
</div>

<div class="username-comment">
  <<%= current_user.nickname %><span>さんの投稿</span>></%>
</div>

<%= form_for [@product] do |f| %>
  <div style="margin: 8px ">
    <%= f.text_field :title, placeholder: '温泉の名前'%>
  </div>
  <div style="margin: 8px ">
    <%= f.text_field :image_url, placeholder: 'urlのコピーを添付'%>
  </div>
  <div style="margin: 8px ">
    <%= f.text_area :explain, placeholder: '温泉の説明（概要）', style: 'width: 100%; height: 200px;' %>
  </div>
  <div style="margin: 8px">
    <%= f.text_field :access, placeholder: 'アクセス', style: 'width: 350px; height: 20px'%>
  </div>
  <div style="float:right; margin: 8px 20px">
    <%= f.submit "送信", class: "btn btn-primary withripple" %>
  </div>
<% end %>
</div>

app/views/products/show.html.erb
 <div class="main_wrapper" style="padding:15px">
  <h3><詳細ページ></h3>
   <div class="name-creater">
    <h4><%= @product.user.nickname %><span>さんによる投稿情報です</span></%></h4>
   </div>
  <div class="shousai" style="clear:right">
     <div class="shousai-title">
     <%= @product.title %>
     </div>
    <div class="shousai-image" style="text-align:center">
     <img src="<%= @product.image_url %>" alt="<%= @product.title %>"width="750" height="350">
    </div>
     <div class="shousai-explain">
      <%= @product.explain %>
     </div>
      
      <div class="toko-page-flame" style="float:right">
      <a href="/products/<%= @product.id %>/reviews/new" title="<%= @product.title%>">
       コメントする
       </a>
       </div>
  </div>
  
   <div class="comment-show">
    <h2>口コミ</h2>
      <% @product.reviews.each do |review| %>
       <div class="comment-review">
         <div classs="comment-user">
          <div class="comment-image">
             <p class="text-small">
             <span class="rating-star"><i class="star-actived rate-<%= review.rate %>0"></i></span>
             </p>
          </div>
         </div>
          
          <div class="comment-info">
            <div class="comment-username"><span><<%= review.user.nickname %>さん></span></%></div>
            <div class="comment-title">
              <%= review.title %></div>
            <div class="comment-comment"><%= review.review%></div>
          </div>
        </div>
         <% end %>
   </div>
 </div>

app/views/reviews/edit.html.erb
<div class="contents row">
  <%= form_tag("/reviews/#{@review.id}", method: :patch ) do %>
    <h3>
      編集する
    </h3>
    
</div>

app/views/reviews/new.html.erb
<div class="contents row" style="padding:10px">
    <h3><投稿ページ></h3>
  <div class="toukou-page">
    <div class="toukou-image" style="text-align:center">
     <img src="<%= @product.image_url %>" alt="<%= @product.title %>"width="750" height="350">
    </div>
    <div class="shousai-explain">
      <%= @product.explain %>
     </div>
  </div>
</div>

<%= form_for [@product, @review,] do |f| %>
          <div style="margin: 8px 0">
            <%= f.label :評価, style: { 'margin-right' => 8 } %>
            <%= f.number_field :rate, placeholder: '評価', value: 1, max: 5, min: 1, html: { class: "evaluation", style: 'text-align: right;' } %>
          </div>
          <div style="margin: 8px 0">
            <%= f.text_field :title, placeholder: 'タイトル'%>
          </div>
          <div style="margin: 8px 0">
            <%= f.text_area :review, placeholder: 'レビューを書いてね！', style: 'width: 100%; height: 200px;' %>
          </div>
          <div class="row">
            <div class="col10 push1">
              <%= button_tag type: "submit", class: "btn btn--block" do %>
              投稿する<i class="icon-arrow-right"></i>
              <% end %>
            </div>
          </div>
          <% end %>

app/views/users/show.html.erb
<div class="main_wrapper" style="padding:15px">
    <h4><ユーザーページ></h4>
  <div class="user-info">
     <div class="user-flame">
       <div class="user-image" ><%= image_tag current_user.image %></div>
       <div class="user-text">
          <h2><%= current_user.nickname %><span>さん</span></h2><br><br><br></br></br></br>
          <div class="comment-count">
              <span>コメント数<%= @count_reviews.count %>件</span>
          </div>
      </div>
     </div>
  </div>
  
  <div class="user-review">
      <h4><<%= current_user.nickname %><span>さんの投稿履歴</span>></%></h4>
         <%  @reviews.each do |review| %>
       <div class="comment-review">
         <div classs="comment-user">
          <div class="comment-image">
            <img src="<%= review.product.image_url %>" width="100" height="100"></img>
             <div class="comment-image-title"><%= review.product.title.truncate(7)%></div>
             <p class="text-small">
             <span class="rating-star"><i class="star-actived rate-<%= review.rate %>0"></i></span>
             </p>
          </div>
         </div>
          
          <div class="comment-info">
            <div class="comment-title">
              <%= review.title %></div>
            <div class="comment-comment"><%= review.review%></div>
          </div>
        </div>
         <% end %>
         <%= paginate(@reviews)%>
  </div>
</div>